### ISSUE TITLE
Class FTP adding Directory listing

### ISSUE THREAD

**Issue by lintalist** [jNizM/AHK_Scripts#2]
Hello,

your FTP class is useful :+1:  Do you plan on adding adding "get directory listing" function? It seems you need to do that in three steps, ftpfindfirst -> findnextfile -> closing it, See https://docs.microsoft.com/en-us/windows/desktop/api/wininet/nf-wininet-ftpfindfirstfilew 

AutoIt UDF @ https://www.autoitscript.com/forum/topic/94212-ftp-udf/ with these three funcs:

* _FTP_FileFindFirst
* _FTP_FileFindNext
* _FTP_FileFindClose

might be useful for a quick conversion / guidance.

**Comment by joedf** [comment]
The used core WinAPI functions seem to be:

- `FtpFindFirstFile` : https://msdn.microsoft.com/library/ms909388
- `InternetFindNextFile` : https://msdn.microsoft.com/library/ms909422
- `InternetCloseHandle` : https://msdn.microsoft.com/library/ms909415

**Comment by jNizM** [comment]
A full rewritten class can be found here -> https://github.com/jNizM/Class_FTP
