### ISSUE TITLE
base64.ahk param

### ISSUE THREAD

**Issue by flossy83** [jNizM/AHK_Scripts#3]
The third parameter of DllCall CryptBinaryToString should be 0x40000001 otherwise it will put a CRLF at the end.  But it doesn't support Windows Server 2003 and Windows XP.

**Comment by tdalon** [comment]
Yes. The function b64Encode is buggy for longer stings: it will group the string with CRLF.
As fix I clean up the output with RegExReplace(str,"(\n|\r)")

Proper fix: https://github.com/tdalon/ahk/blob/main/Lib/b64Encode.ahk

**Comment by jNizM** [comment]
Fixed with https://github.com/jNizM/AHK_Scripts/commit/cea509c0c25c0d7c26ca7381b115013997e257d4
